"""update on the db

Revision ID: a2a2d01e48b3
Revises: 3229a2027b0e
Create Date: 2024-08-29 21:50:33.246196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2a2d01e48b3'
down_revision = '3229a2027b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_room', sa.String(length=150), nullable=False))
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', mysql.VARCHAR(length=64), nullable=False))
        batch_op.drop_column('chat_room')

    # ### end Alembic commands ###
